from __future__ import annotations

from datetime import timedelta

from .db import SQLiteStorage, utc_now
from .models import ChannelType


def seed_mvp_data(storage: SQLiteStorage) -> None:
    now = utc_now()

    storage.reset_all_data()
    storage.insert_products(
        [
            ("p1", "Премиальная карта", "cards", "low", "medium", "RUB"),
            ("p2", "Инвест-счет", "investment", "high", "high", "RUB"),
            ("p3", "Премиальный вклад", "deposits", "low", "medium", "RUB"),
            ("p4", "Страхование путешествий", "insurance", "low", "high", "RUB"),
            ("p5", "Брокерский счет", "brokerage", "high", "high", "USD"),
        ]
    )
    storage.insert_clients(
        [
            (
                "c1",
                "Иван Петров",
                "Alfa Only",
                "moderate",
                "m1",
                42,
                "Москва",
                "chat",
                "married",
                "IT-предприниматель",
                "high",
                12500000.0,
                950000.0,
                "medium",
                (now - timedelta(days=7)).isoformat(),
                (now + timedelta(days=2)).isoformat(),
                "Интерес к инвестициям, ценит быстрые ответы и персональные предложения.",
                "investments|premium-card|family",
            ),
            (
                "c2",
                "Ольга Смирнова",
                "Alfa Only",
                "conservative",
                "m1",
                51,
                "Санкт-Петербург",
                "call",
                "married",
                "Финансовый директор",
                "very_high",
                28700000.0,
                2100000.0,
                "low",
                (now - timedelta(days=2)).isoformat(),
                (now + timedelta(hours=5)).isoformat(),
                "Ожидает проактивного сервиса, интересуется сохранением капитала и structured deals.",
                "retention|deposit|vip",
            ),
            (
                "c3",
                "Алексей Орлов",
                "Alfa Only",
                "aggressive",
                "m2",
                36,
                "Казань",
                "meeting",
                "single",
                "Основатель e-commerce бизнеса",
                "high",
                9400000.0,
                430000.0,
                "medium",
                (now - timedelta(days=10)).isoformat(),
                (now + timedelta(days=1)).isoformat(),
                "Открыт к риску, интересуется валютными инструментами и идеями для роста капитала.",
                "fx|growth|brokerage",
            ),
            (
                "c4",
                "Мария Кузнецова",
                "Alfa Only",
                "moderate",
                "m2",
                45,
                "Екатеринбург",
                "chat",
                "married",
                "Юрист",
                "medium",
                6200000.0,
                380000.0,
                "high",
                (now - timedelta(days=20)).isoformat(),
                (now + timedelta(hours=10)).isoformat(),
                "Реже отвечает, нужно мягкое удержание и короткие follow-up сообщения.",
                "churn-risk|soft-contact|insurance",
            ),
            (
                "c5",
                "Дмитрий Волков",
                "Alfa Only",
                "conservative",
                "m1",
                58,
                "Москва",
                "call",
                "married",
                "Собственник производства",
                "very_high",
                41300000.0,
                5100000.0,
                "low",
                (now - timedelta(days=3)).isoformat(),
                (now + timedelta(days=4)).isoformat(),
                "Большой остаток на счете, готов обсуждать размещение ликвидности и премиальные сервисы.",
                "liquidity|deposit|wealth",
            ),
            (
                "c6",
                "Елена Федорова",
                "Alfa Only",
                "moderate",
                "m2",
                33,
                "Новосибирск",
                "chat",
                "single",
                "Топ-менеджер в IT",
                "high",
                7700000.0,
                620000.0,
                "medium",
                (now - timedelta(days=1)).isoformat(),
                (now + timedelta(days=3)).isoformat(),
                "Быстро реагирует в чате, интересуется travel-benefits и инвестиционными подборками.",
                "travel|premium-card|active-chat",
            ),
        ]
    )
    storage.insert_client_products(
        [
            ("c1", "p1", "active", 240000.0, (now - timedelta(days=800)).isoformat()),
            ("c1", "p2", "active", 3100000.0, (now - timedelta(days=380)).isoformat()),
            ("c2", "p1", "active", 520000.0, (now - timedelta(days=1200)).isoformat()),
            ("c2", "p3", "active", 12500000.0, (now - timedelta(days=160)).isoformat()),
            ("c3", "p2", "active", 1850000.0, (now - timedelta(days=220)).isoformat()),
            ("c3", "p5", "active", 720000.0, (now - timedelta(days=140)).isoformat()),
            ("c4", "p4", "active", 35000.0, (now - timedelta(days=95)).isoformat()),
            ("c5", "p1", "active", 610000.0, (now - timedelta(days=900)).isoformat()),
            ("c5", "p3", "active", 18900000.0, (now - timedelta(days=60)).isoformat()),
            ("c6", "p1", "active", 180000.0, (now - timedelta(days=300)).isoformat()),
            ("c6", "p2", "active", 960000.0, (now - timedelta(days=200)).isoformat()),
            ("c6", "p4", "active", 42000.0, (now - timedelta(days=25)).isoformat()),
        ]
    )
    storage.insert_conversations(
        [
            ("conv1", "c1", ChannelType.chat.value, "Инвестиционные идеи", (now - timedelta(days=1)).isoformat()),
            ("conv2", "c2", ChannelType.call.value, "Обновление портфеля", (now - timedelta(hours=6)).isoformat()),
            ("conv5", "c3", ChannelType.chat.value, "Валютные идеи и брокерский счет", (now - timedelta(days=2)).isoformat()),
            ("conv3", "c4", ChannelType.chat.value, "Возврат в коммуникацию", (now - timedelta(days=6)).isoformat()),
            ("conv6", "c5", ChannelType.chat.value, "Размещение свободной ликвидности", (now - timedelta(days=1, hours=4)).isoformat()),
            ("conv4", "c6", ChannelType.chat.value, "Премиальные travel-benefits", (now - timedelta(hours=18)).isoformat()),
        ]
    )
    storage.insert_messages(
        [
            (
                "msg1",
                "conv1",
                "client",
                "Добрый день, хочу обсудить варианты размещения средств.",
                (now - timedelta(days=1, minutes=20)).isoformat(),
            ),
            (
                "msg2",
                "conv1",
                "manager",
                "Добрый день! Подготовлю варианты и вернусь с предложениями.",
                (now - timedelta(days=1, minutes=18)).isoformat(),
            ),
            (
                "msg9",
                "conv1",
                "client",
                "Интересуют варианты без слишком высокого риска, но с доходностью выше вклада.",
                (now - timedelta(days=1, minutes=11)).isoformat(),
            ),
            (
                "msg10",
                "conv1",
                "manager",
                "Понял вас. Тогда могу предложить комбинацию из консервативной части и небольшой доли инвест-идей.",
                (now - timedelta(days=1, minutes=8)).isoformat(),
            ),
            (
                "msg11",
                "conv1",
                "client",
                "Да, такой вариант уже звучит ближе. И хотелось бы понять, какая ликвидность у этих решений.",
                (now - timedelta(days=1, minutes=5)).isoformat(),
            ),
            (
                "msg12",
                "conv1",
                "manager",
                "Сделаю короткую подборку с тремя сценариями и отдельно отмечу, где можно быстро выйти в кэш.",
                (now - timedelta(days=1, minutes=2)).isoformat(),
            ),
            (
                "msg3",
                "conv2",
                "manager",
                "Уточняю, удобно ли сегодня обсудить обновление портфеля.",
                (now - timedelta(hours=6, minutes=15)).isoformat(),
            ),
            (
                "msg4",
                "conv2",
                "client",
                "Да, после 16:00 смогу созвониться.",
                (now - timedelta(hours=6, minutes=10)).isoformat(),
            ),
            (
                "msg13",
                "conv2",
                "manager",
                "Отлично. Тогда подготовлю сравнение по вкладу, облигационной части и защитным стратегиям.",
                (now - timedelta(hours=5, minutes=55)).isoformat(),
            ),
            (
                "msg14",
                "conv2",
                "client",
                "Да, и прошу сделать акцент на сохранности капитала, без лишнего риска.",
                (now - timedelta(hours=5, minutes=48)).isoformat(),
            ),
            (
                "msg15",
                "conv2",
                "manager",
                "Принято. Сфокусируюсь на консервативном профиле и отдельно отмечу ожидаемую доходность.",
                (now - timedelta(hours=5, minutes=42)).isoformat(),
            ),
            (
                "msg16",
                "conv5",
                "client",
                "Добрый вечер. Смотрю на валютные инструменты, но не хочу заходить слишком агрессивно.",
                (now - timedelta(days=2, minutes=35)).isoformat(),
            ),
            (
                "msg17",
                "conv5",
                "manager",
                "Понимаю. Можем рассмотреть поэтапный вход через брокерский счет и ограничить долю валютной части.",
                (now - timedelta(days=2, minutes=31)).isoformat(),
            ),
            (
                "msg18",
                "conv5",
                "client",
                "Мне важно, чтобы был понятный план: сколько завести, во что распределить и когда смотреть результат.",
                (now - timedelta(days=2, minutes=25)).isoformat(),
            ),
            (
                "msg19",
                "conv5",
                "manager",
                "Сделаю для вас простой сценарий на 3 шага: стартовая сумма, базовое распределение и точки пересмотра портфеля.",
                (now - timedelta(days=2, minutes=20)).isoformat(),
            ),
            (
                "msg5",
                "conv3",
                "manager",
                "Мария, добрый день. Хотел коротко уточнить, актуален ли для вас вопрос страховой защиты перед поездками.",
                (now - timedelta(days=6, minutes=25)).isoformat(),
            ),
            (
                "msg6",
                "conv3",
                "client",
                "Сейчас не до этого, вернусь позже.",
                (now - timedelta(days=6, minutes=20)).isoformat(),
            ),
            (
                "msg20",
                "conv3",
                "manager",
                "Хорошо, не буду перегружать. Напишу ближе к дате поездки и пришлю короткий вариант без лишних деталей.",
                (now - timedelta(days=6, minutes=14)).isoformat(),
            ),
            (
                "msg21",
                "conv3",
                "client",
                "Спасибо, так будет комфортнее.",
                (now - timedelta(days=6, minutes=11)).isoformat(),
            ),
            (
                "msg22",
                "conv6",
                "manager",
                "Дмитрий, добрый день. Вижу крупный остаток на счете, хотел предложить коротко обсудить размещение ликвидности.",
                (now - timedelta(days=1, hours=4, minutes=40)).isoformat(),
            ),
            (
                "msg23",
                "conv6",
                "client",
                "Добрый. Да, можно, но без долгой презентации. Хочу быстро понять, где сейчас разумнее разместиться.",
                (now - timedelta(days=1, hours=4, minutes=33)).isoformat(),
            ),
            (
                "msg24",
                "conv6",
                "manager",
                "Тогда подготовлю короткое сравнение: премиальный вклад, облигационная альтернатива и гибридный вариант.",
                (now - timedelta(days=1, hours=4, minutes=25)).isoformat(),
            ),
            (
                "msg25",
                "conv6",
                "client",
                "Супер, только сразу дайте срок, ликвидность и ожидаемую доходность в одном сообщении.",
                (now - timedelta(days=1, hours=4, minutes=18)).isoformat(),
            ),
            (
                "msg7",
                "conv4",
                "manager",
                "Елена, вижу, что у вас скоро поездка. Могу подобрать benefits по премиальной карте.",
                (now - timedelta(hours=18, minutes=35)).isoformat(),
            ),
            (
                "msg8",
                "conv4",
                "client",
                "Да, это актуально, особенно lounge и страховка.",
                (now - timedelta(hours=18, minutes=30)).isoformat(),
            ),
            (
                "msg26",
                "conv4",
                "manager",
                "Тогда подберу пакет, где будут проходы в lounge, travel-страховка и приоритетный сервис в поездках.",
                (now - timedelta(hours=18, minutes=23)).isoformat(),
            ),
            (
                "msg27",
                "conv4",
                "client",
                "Идеально. Если можно, пришлите в коротком формате, чтобы я быстро посмотрела с телефона.",
                (now - timedelta(hours=18, minutes=17)).isoformat(),
            ),
            (
                "msg28",
                "conv4",
                "manager",
                "Сделаю краткий вариант сообщением и отдельно смогу потом объяснить детали, если потребуется.",
                (now - timedelta(hours=18, minutes=11)).isoformat(),
            ),
        ]
    )
    storage.insert_crm_notes(
        [
            (
                "n1",
                "c2",
                "m1",
                "t7",
                "Созвон состоялся. Клиент подтвердил интерес к продлению вклада и попросил сравнение с инвестиционным мандатом.",
                "follow_up",
                ChannelType.call.value,
                (now + timedelta(days=2)).isoformat(),
                (now - timedelta(hours=2)).isoformat(),
            ),
            (
                "n2",
                "c4",
                "m2",
                None,
                "Клиент ответил сдержанно, просит не перегружать сообщениями. Нужен мягкий follow-up через несколько дней.",
                "pending",
                ChannelType.chat.value,
                (now + timedelta(days=4)).isoformat(),
                (now - timedelta(days=1)).isoformat(),
            ),
        ]
    )
    storage.insert_follow_ups(
        [
            (
                "f1",
                "c2",
                "n1",
                (now + timedelta(days=2)).isoformat(),
                "Подготовить сравнение вклада и инвест-мандата",
                0,
            ),
            (
                "f2",
                "c4",
                "n2",
                (now + timedelta(days=4)).isoformat(),
                "Вернуться с мягким сообщением про страховую защиту",
                0,
            ),
        ]
    )
    storage.insert_feedback(
        [
            (
                "fb1",
                "rec-portfolio-1",
                "m1",
                "priority_recommendation",
                "accepted",
                "Логика понятна, беру в работу.",
                (now - timedelta(hours=3)).isoformat(),
            ),
            (
                "fb2",
                "rec-retention-4",
                "m2",
                "next_best_action",
                "edited",
                "Сделаю более мягкий контакт, чем предлагалось.",
                (now - timedelta(hours=8)).isoformat(),
            ),
        ]
    )
