from __future__ import annotations

from datetime import timedelta

from .db import SQLiteStorage, utc_now
from .models import ChannelType


def _message_rows(conversation_id: str, items: list[tuple[str, str, timedelta]]) -> list[tuple[str, str, str, str, str]]:
    rows: list[tuple[str, str, str, str, str]] = []
    for index, (sender, text, offset) in enumerate(items, start=1):
        rows.append((f"{conversation_id}-msg-{index}", conversation_id, sender, text, offset.isoformat()))
    return rows


def seed_mvp_data(storage: SQLiteStorage) -> None:
    now = utc_now()

    storage.reset_all_data()
    storage.insert_products(
        [
            ("p1", "Премиальная карта", "cards", "low", "medium", "RUB"),
            ("p2", "Инвест-счет", "investment", "high", "high", "RUB"),
            ("p3", "Премиальный вклад", "deposits", "low", "medium", "RUB"),
            ("p4", "Страхование путешествий", "insurance", "low", "high", "RUB"),
            ("p5", "Брокерский счет", "brokerage", "high", "high", "USD"),
        ]
    )
    storage.insert_clients(
        [
            (
                "c1",
                "Иван Петров",
                "Alfa Only",
                "moderate",
                "m1",
                42,
                "Москва",
                "chat",
                "married",
                "IT-предприниматель",
                "high",
                12500000.0,
                950000.0,
                "medium",
                (now - timedelta(days=7)).isoformat(),
                (now + timedelta(days=2)).isoformat(),
                "Интерес к инвестициям, ценит быстрые ответы и персональные предложения.",
                None,
                None,
                "investments|premium-card|family",
            ),
            (
                "c2",
                "Ольга Смирнова",
                "Alfa Only",
                "conservative",
                "m1",
                51,
                "Санкт-Петербург",
                "call",
                "married",
                "Финансовый директор",
                "very_high",
                28700000.0,
                2100000.0,
                "low",
                (now - timedelta(days=2)).isoformat(),
                (now + timedelta(hours=5)).isoformat(),
                "Ожидает проактивного сервиса, интересуется сохранением капитала и structured deals.",
                None,
                None,
                "retention|deposit|vip",
            ),
            (
                "c3",
                "Алексей Орлов",
                "Alfa Only",
                "aggressive",
                "m2",
                36,
                "Казань",
                "meeting",
                "single",
                "Основатель e-commerce бизнеса",
                "high",
                9400000.0,
                430000.0,
                "medium",
                (now - timedelta(days=10)).isoformat(),
                (now + timedelta(days=1)).isoformat(),
                "Открыт к риску, интересуется валютными инструментами и идеями для роста капитала.",
                None,
                None,
                "fx|growth|brokerage",
            ),
            (
                "c4",
                "Мария Кузнецова",
                "Alfa Only",
                "moderate",
                "m2",
                45,
                "Екатеринбург",
                "chat",
                "married",
                "Юрист",
                "medium",
                6200000.0,
                380000.0,
                "high",
                (now - timedelta(days=20)).isoformat(),
                (now + timedelta(hours=10)).isoformat(),
                "Реже отвечает, нужно мягкое удержание и короткие follow-up сообщения.",
                None,
                None,
                "churn-risk|soft-contact|insurance",
            ),
            (
                "c5",
                "Дмитрий Волков",
                "Alfa Only",
                "conservative",
                "m1",
                58,
                "Москва",
                "call",
                "married",
                "Собственник производства",
                "very_high",
                41300000.0,
                5100000.0,
                "low",
                (now - timedelta(days=3)).isoformat(),
                (now + timedelta(days=4)).isoformat(),
                "Большой остаток на счете, готов обсуждать размещение ликвидности и премиальные сервисы.",
                None,
                None,
                "liquidity|deposit|wealth",
            ),
            (
                "c6",
                "Елена Федорова",
                "Alfa Only",
                "moderate",
                "m2",
                33,
                "Новосибирск",
                "chat",
                "single",
                "Топ-менеджер в IT",
                "high",
                7700000.0,
                620000.0,
                "medium",
                (now - timedelta(days=1)).isoformat(),
                (now + timedelta(days=3)).isoformat(),
                "Быстро реагирует в чате, интересуется travel-benefits и инвестиционными подборками.",
                None,
                None,
                "travel|premium-card|active-chat",
            ),
            (
                "c7",
                "Наталья Белова",
                "Alfa Only",
                "moderate",
                "m1",
                39,
                "Москва",
                "chat",
                "married",
                "Партнер в консалтинге",
                "high",
                11800000.0,
                1450000.0,
                "medium",
                (now - timedelta(days=4)).isoformat(),
                (now + timedelta(hours=9)).isoformat(),
                "Ожидает короткие персональные follow-up, часто реагирует на сервисные и travel-темы.",
                None,
                None,
                "travel|service|campaign",
            ),
            (
                "c8",
                "Сергей Лебедев",
                "Alfa Only",
                "conservative",
                "m1",
                54,
                "Москва",
                "call",
                "married",
                "Управляющий партнер",
                "very_high",
                33500000.0,
                3800000.0,
                "high",
                (now - timedelta(days=9)).isoformat(),
                (now + timedelta(hours=7)).isoformat(),
                "Нужен дисциплинированный контакт по ликвидности и удержанию части средств в банке.",
                None,
                None,
                "retention|liquidity|vip",
            ),
            (
                "c9",
                "Андрей Морозов",
                "Alfa Only",
                "aggressive",
                "m1",
                41,
                "Москва",
                "chat",
                "married",
                "Партнер в digital-агентстве",
                "high",
                15400000.0,
                2750000.0,
                "high",
                (now - timedelta(days=12)).isoformat(),
                (now + timedelta(hours=6)).isoformat(),
                "Интересовался FX и диверсификацией, но резко теряет интерес, если чувствует давление или общий pitch.",
                None,
                None,
                "fx|churn-risk|silent",
            ),
            (
                "c10",
                "Татьяна Жукова",
                "Alfa Only",
                "conservative",
                "m2",
                49,
                "Санкт-Петербург",
                "call",
                "married",
                "COO в производственной группе",
                "very_high",
                21900000.0,
                4600000.0,
                "high",
                (now - timedelta(days=1)).isoformat(),
                (now + timedelta(hours=3)).isoformat(),
                "Недовольна качеством сервиса и рассматривает перевод части остатков. Любой sales push в такой момент раздражает.",
                None,
                None,
                "negative-tone|retention|service",
            ),
            (
                "c11",
                "Павел Соколов",
                "Alfa Only",
                "moderate",
                "m1",
                34,
                "Нижний Новгород",
                "chat",
                "single",
                "Руководитель продаж",
                "medium",
                3200000.0,
                190000.0,
                "medium",
                (now - timedelta(days=15)).isoformat(),
                (now + timedelta(days=1)).isoformat(),
                None,
                None,
                None,
                "insufficient-data|new-client|salary",
            ),
            (
                "c12",
                "Кира Новикова",
                "Alfa Only",
                "moderate",
                "m2",
                38,
                "Москва",
                "call",
                "single",
                "Собственник студии дизайна",
                "high",
                18400000.0,
                6800000.0,
                "low",
                (now - timedelta(hours=12)).isoformat(),
                (now + timedelta(hours=4)).isoformat(),
                "Нужна парковка ликвидности перед сделкой, но потом хочет перейти к инвестиционному плану без лишней суеты.",
                None,
                None,
                "liquidity|investments|deal-window",
            ),
            (
                "c13",
                "Роман Гусев",
                "Alfa Only",
                "conservative",
                "m1",
                57,
                "Самара",
                "call",
                "married",
                "Собственник строительной компании",
                "very_high",
                24700000.0,
                8200000.0,
                "high",
                (now - timedelta(days=27)).isoformat(),
                (now + timedelta(hours=2)).isoformat(),
                "Почти перестал отвечать, но ранее сам поднимал тему краткосрочной ликвидности. Нужен очень аккуратный возврат в диалог.",
                None,
                None,
                "silent-client|liquidity|retention",
            ),
            (
                "c14",
                "Анна Троицкая",
                "Alfa Only",
                "moderate",
                "m2",
                37,
                "Краснодар",
                "chat",
                "married",
                "Руководитель HR-направления",
                "medium",
                8100000.0,
                540000.0,
                "medium",
                (now - timedelta(days=5)).isoformat(),
                (now + timedelta(hours=20)).isoformat(),
                "Семейный контур, travel и insurance интересны, но реагирует коротко и быстро устает от сложных условий.",
                None,
                None,
                "family|travel|insurance",
            ),
            (
                "c15",
                "Виктор Самойлов",
                "Alfa Only",
                "aggressive",
                "m1",
                46,
                "Москва",
                "meeting",
                "married",
                "Экс-партнер инвестиционной компании",
                "very_high",
                31200000.0,
                14500000.0,
                "medium",
                (now - timedelta(days=3)).isoformat(),
                (now + timedelta(hours=5)).isoformat(),
                "После продажи доли в бизнесе хочет investment plan, но опасается плохого тайминга и захода на пике рынка.",
                None,
                None,
                "investment-intent|timing-risk|brokerage",
            ),
        ]
    )
    storage.insert_client_products(
        [
            ("c1", "p1", "active", 240000.0, (now - timedelta(days=800)).isoformat()),
            ("c1", "p2", "active", 3100000.0, (now - timedelta(days=380)).isoformat()),
            ("c2", "p1", "active", 520000.0, (now - timedelta(days=1200)).isoformat()),
            ("c2", "p3", "active", 12500000.0, (now - timedelta(days=160)).isoformat()),
            ("c3", "p2", "active", 1850000.0, (now - timedelta(days=220)).isoformat()),
            ("c3", "p5", "active", 720000.0, (now - timedelta(days=140)).isoformat()),
            ("c4", "p4", "active", 35000.0, (now - timedelta(days=95)).isoformat()),
            ("c5", "p1", "active", 610000.0, (now - timedelta(days=900)).isoformat()),
            ("c5", "p3", "active", 18900000.0, (now - timedelta(days=60)).isoformat()),
            ("c6", "p1", "active", 180000.0, (now - timedelta(days=300)).isoformat()),
            ("c6", "p2", "active", 960000.0, (now - timedelta(days=200)).isoformat()),
            ("c6", "p4", "active", 42000.0, (now - timedelta(days=25)).isoformat()),
            ("c7", "p1", "active", 260000.0, (now - timedelta(days=430)).isoformat()),
            ("c7", "p4", "active", 56000.0, (now - timedelta(days=120)).isoformat()),
            ("c8", "p1", "active", 720000.0, (now - timedelta(days=980)).isoformat()),
            ("c8", "p3", "active", 16400000.0, (now - timedelta(days=210)).isoformat()),
            ("c9", "p1", "active", 230000.0, (now - timedelta(days=640)).isoformat()),
            ("c9", "p5", "active", 1260000.0, (now - timedelta(days=320)).isoformat()),
            ("c10", "p1", "active", 480000.0, (now - timedelta(days=850)).isoformat()),
            ("c10", "p3", "active", 9700000.0, (now - timedelta(days=140)).isoformat()),
            ("c11", "p1", "active", 92000.0, (now - timedelta(days=200)).isoformat()),
            ("c12", "p1", "active", 340000.0, (now - timedelta(days=500)).isoformat()),
            ("c12", "p3", "active", 5200000.0, (now - timedelta(days=90)).isoformat()),
            ("c13", "p1", "active", 510000.0, (now - timedelta(days=760)).isoformat()),
            ("c13", "p3", "active", 10300000.0, (now - timedelta(days=240)).isoformat()),
            ("c14", "p1", "active", 210000.0, (now - timedelta(days=410)).isoformat()),
            ("c14", "p4", "active", 30000.0, (now - timedelta(days=75)).isoformat()),
            ("c15", "p5", "active", 2460000.0, (now - timedelta(days=110)).isoformat()),
        ]
    )
    storage.insert_tasks(
        [
            (
                "task-1",
                "c2",
                "Подготовить рамку к звонку по портфелю",
                "Собрать короткое сравнение по вкладу, защитной облигационной части и structured idea до звонка.",
                "in_progress",
                (now + timedelta(hours=2)).isoformat(),
                (now - timedelta(hours=1)).isoformat(),
                ChannelType.call.value,
                "high",
                "portfolio_review",
                "Подвести клиента к согласованному обновлению портфеля без избыточного риска",
                "sfa",
                "conv2",
                "p3",
            ),
            (
                "task-2",
                "c1",
                "Отправить клиенту компактное сравнение сценариев",
                "Закрыть обещанный follow-up по 3 вариантам размещения и показать ликвидность в одном сообщении.",
                "new",
                (now + timedelta(hours=18)).isoformat(),
                (now - timedelta(hours=3)).isoformat(),
                ChannelType.chat.value,
                "high",
                "offer_follow_up",
                "Перевести интерес клиента к инвестициям в следующий осмысленный шаг",
                "crm",
                "conv1",
                "p3",
            ),
            (
                "task-3",
                "c5",
                "Подготовить вариант размещения ликвидности",
                "Собрать короткий оффер по размещению свободного остатка и выделить быстрый выход в кэш.",
                "new",
                (now + timedelta(hours=8)).isoformat(),
                (now - timedelta(hours=4)).isoformat(),
                ChannelType.chat.value,
                "high",
                "product_pitch",
                "Сконвертировать свободную ликвидность клиента в продуктовый follow-up",
                "sfa",
                "conv6",
                "p3",
            ),
            (
                "task-4",
                "c4",
                "Мягкий follow-up перед поездкой",
                "Вернуться коротким сообщением без давления и подтвердить комфортный формат общения только в чате.",
                "new",
                (now + timedelta(hours=6)).isoformat(),
                (now - timedelta(days=1)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "retention_follow_up",
                "Удержать клиента в коммуникации и не допустить выпадения из поля внимания",
                "crm",
                "conv3",
                "p4",
            ),
            (
                "task-5",
                "c3",
                "Назначить встречу по валютным идеям",
                "После отправки базового плана предложить 2 слота на следующую неделю и зафиксировать очную встречу.",
                "in_progress",
                (now + timedelta(days=1, hours=3)).isoformat(),
                (now - timedelta(hours=5)).isoformat(),
                ChannelType.meeting.value,
                "medium",
                "meeting_conversion",
                "Перевести интерес к валютным идеям в очную консультацию",
                "crm",
                "conv5",
                "p5",
            ),
            (
                "task-6",
                "c6",
                "Сделать короткий travel-benefits follow-up",
                "Подобрать лаконичный follow-up с акцентом на travel-пакет и инвестиционные подборки.",
                "new",
                (now + timedelta(hours=26)).isoformat(),
                (now - timedelta(hours=2)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "offer_follow_up",
                "Поддержать высокий темп коммуникации и расширить интерес клиента",
                "sfa",
                "conv4",
                "p1",
            ),
            (
                "task-7",
                "c7",
                "Отправить подборку travel-сервиса",
                "Подготовить короткий follow-up по travel-benefits и сервисным опциям без перегруза условиями.",
                "new",
                (now + timedelta(hours=9)).isoformat(),
                (now - timedelta(hours=2, minutes=30)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "service_follow_up",
                "Удержать высокий интерес к сервису и перевести его в follow-up по премиальной карте",
                "crm",
                "conv7",
                "p1",
            ),
            (
                "task-8",
                "c8",
                "Согласовать окно по ликвидности",
                "Собрать короткий call-brief по размещению остатка и удержанию части средств в банке.",
                "new",
                (now + timedelta(hours=7)).isoformat(),
                (now - timedelta(hours=4, minutes=20)).isoformat(),
                ChannelType.call.value,
                "high",
                "retention_follow_up",
                "Не потерять окно для удержания ликвидности и обновления краткосрочного размещения",
                "sfa",
                "conv8",
                "p3",
            ),
            (
                "task-9",
                "c1",
                "Разобрать отдельный запрос по сервису карты",
                "После продуктового сценария коротко закрыть сервисный вопрос по премиальной карте и не смешивать его с инвест-оффером.",
                "new",
                (now + timedelta(hours=20)).isoformat(),
                (now - timedelta(hours=1, minutes=40)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "service_follow_up",
                "Сохранить точность кейса и не смешать сервисный запрос с инвестиционной коммуникацией",
                "crm",
                "conv1b",
                "p1",
            ),
            (
                "task-10",
                "c9",
                "Вернуть клиента в FX-диалог без давления",
                "Собрать короткий staged follow-up по FX-диверсификации: показать идею, но не давить на немедленное решение.",
                "new",
                (now + timedelta(hours=5)).isoformat(),
                (now - timedelta(hours=5, minutes=10)).isoformat(),
                ChannelType.chat.value,
                "high",
                "retention_follow_up",
                "Сохранить investment intent клиента с высоким churn-риском и не потерять окно для возврата в диалог",
                "crm",
                "conv10",
                "p5",
            ),
            (
                "task-11",
                "c10",
                "Снять негатив после сервисного сбоя",
                "Сначала вернуть доверие после жалобы на сервис, потом отдельно договориться о коротком звонке по ликвидности.",
                "new",
                (now + timedelta(hours=2)).isoformat(),
                (now - timedelta(hours=2, minutes=40)).isoformat(),
                ChannelType.call.value,
                "high",
                "service_recovery",
                "Остановить churn и восстановить доверие до любого продуктового предложения",
                "sfa",
                "conv11",
                "p1",
            ),
            (
                "task-12",
                "c11",
                "Собрать недостающий профиль клиента",
                "До любого pitch нужно уточнить горизонт, свободную ликвидность и интерес к инвестициям. Сейчас данных недостаточно.",
                "new",
                (now + timedelta(hours=9)).isoformat(),
                (now - timedelta(hours=4, minutes=45)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "discovery_follow_up",
                "Не пушить продукт до прояснения базовых данных клиента и контекста его запроса",
                "crm",
                "conv12",
                None,
            ),
            (
                "task-13",
                "c12",
                "Подготовить парковку ликвидности перед сделкой",
                "Собрать одно короткое сравнение по размещению средств на коротком горизонте и отдельно обозначить, когда вернуться к investment plan.",
                "new",
                (now + timedelta(hours=3)).isoformat(),
                (now - timedelta(hours=1, minutes=20)).isoformat(),
                ChannelType.call.value,
                "high",
                "liquidity_follow_up",
                "Закрыть краткосрочную liquidity opportunity и не смешать её с долгосрочным investment pitch",
                "sfa",
                "conv13",
                "p3",
            ),
            (
                "task-14",
                "c13",
                "Аккуратный возврат silent клиента",
                "Подготовить очень короткий contact ping по ликвидности и проверить, актуальна ли тема до конца недели.",
                "new",
                (now + timedelta(hours=1, minutes=30)).isoformat(),
                (now - timedelta(hours=6, minutes=15)).isoformat(),
                ChannelType.call.value,
                "high",
                "retention_follow_up",
                "Вернуть в коммуникацию silent клиента с крупным кэш-остатком и высоким риском churn",
                "crm",
                "conv14",
                "p3",
            ),
            (
                "task-15",
                "c14",
                "Подобрать family travel пакет",
                "Сделать короткую подборку из страховки и премиального travel-сервиса в формате, удобном для мобильного чтения.",
                "new",
                (now + timedelta(hours=20)).isoformat(),
                (now - timedelta(hours=3, minutes=35)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "service_follow_up",
                "Сконвертировать семейный travel interest в понятный cross-sell без перегруза условиями",
                "crm",
                "conv15",
                "p4",
            ),
            (
                "task-16",
                "c15",
                "Собрать поэтапный investment plan",
                "Разложить на 3 шага вход в брокерские идеи: что можно сделать сейчас, что позже и где ставить контрольные точки.",
                "new",
                (now + timedelta(hours=4)).isoformat(),
                (now - timedelta(hours=2, minutes=15)).isoformat(),
                ChannelType.meeting.value,
                "high",
                "investment_plan",
                "Перевести высокий investment intent в staged next step, не провоцируя страх плохого тайминга",
                "sfa",
                "conv16",
                "p5",
            ),
            (
                "task-17",
                "c8",
                "Отдельно закрыть сервисный вопрос по премиум-пакету",
                "Не смешивать удержание ликвидности с сервисным вопросом: собрать короткий ответ по benefits отдельным сообщением.",
                "new",
                (now + timedelta(hours=11)).isoformat(),
                (now - timedelta(hours=3, minutes=5)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "service_follow_up",
                "Сохранить точность кейса и не перегружать liquidity conversation сервисной темой",
                "crm",
                "conv17",
                "p1",
            ),
            (
                "task-18",
                "c5",
                "Развести liquidity и long-term intent",
                "Подготовить сообщение, где краткосрочное размещение и долгосрочные investment идеи разведены на два следующих шага.",
                "new",
                (now + timedelta(hours=16)).isoformat(),
                (now - timedelta(hours=5, minutes=20)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "portfolio_review",
                "Не потерять liquidity opportunity и при этом не запутать клиента смешанным pitch по long-term идеям",
                "sfa",
                "conv18",
                "p2",
            ),
            (
                "task-19",
                "c2",
                "Развести сервисный и инвестиционный контур",
                "После обсуждения сервисного сопровождения вернуться коротким сообщением, где отдельно зафиксировать service recovery и отдельно инвестиционный follow-up.",
                "new",
                (now + timedelta(hours=14)).isoformat(),
                (now - timedelta(hours=2, minutes=55)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "service_follow_up",
                "Не смешать service recovery с portfolio review и сохранить доверие клиента",
                "crm",
                "conv9",
                "p1",
            ),
            (
                "task-20",
                "c10",
                "Подготовить компенсационный service follow-up",
                "После звонка вернуть клиенту короткий service recovery message с конкретным статусом и без продуктового предложения.",
                "new",
                (now + timedelta(hours=8)).isoformat(),
                (now - timedelta(hours=1, minutes=50)).isoformat(),
                ChannelType.chat.value,
                "medium",
                "service_follow_up",
                "Закрыть negative tone конкретным сервисным действием и не усиливать churn лишним pitch",
                "crm",
                "conv11",
                "p1",
            ),
        ]
    )
    storage.insert_conversations(
        [
            ("conv1", "c1", ChannelType.chat.value, "Инвестиционные идеи", (now - timedelta(days=2)).isoformat()),
            ("conv1b", "c1", ChannelType.chat.value, "Сервис по премиальной карте", (now - timedelta(hours=8)).isoformat()),
            ("conv2", "c2", ChannelType.call.value, "Обновление портфеля", (now - timedelta(hours=6)).isoformat()),
            ("conv5", "c3", ChannelType.chat.value, "Валютные идеи и брокерский счет", (now - timedelta(days=2)).isoformat()),
            ("conv3", "c4", ChannelType.chat.value, "Возврат в коммуникацию", (now - timedelta(days=6)).isoformat()),
            ("conv6", "c5", ChannelType.chat.value, "Размещение свободной ликвидности", (now - timedelta(days=1, hours=4)).isoformat()),
            ("conv4", "c6", ChannelType.chat.value, "Премиальные travel-benefits", (now - timedelta(hours=18)).isoformat()),
            ("conv7", "c7", ChannelType.chat.value, "Travel-сервис и benefits", (now - timedelta(hours=11)).isoformat()),
            ("conv8", "c8", ChannelType.call.value, "Краткосрочное размещение ликвидности", (now - timedelta(hours=9, minutes=30)).isoformat()),
            ("conv9", "c2", ChannelType.chat.value, "Сервис премиального сопровождения", (now - timedelta(days=3, hours=5)).isoformat()),
            ("conv10", "c9", ChannelType.chat.value, "FX-диверсификация после паузы", (now - timedelta(days=2, hours=4)).isoformat()),
            ("conv11", "c10", ChannelType.call.value, "Негатив по сервису и удержание остатка", (now - timedelta(hours=14)).isoformat()),
            ("conv12", "c11", ChannelType.chat.value, "Первичный контакт без полного профиля", (now - timedelta(days=5, hours=3)).isoformat()),
            ("conv13", "c12", ChannelType.call.value, "Парковка ликвидности перед сделкой", (now - timedelta(hours=10)).isoformat()),
            ("conv14", "c13", ChannelType.call.value, "Возврат silent клиента", (now - timedelta(days=18)).isoformat()),
            ("conv15", "c14", ChannelType.chat.value, "Семейная страховка и travel-пакет", (now - timedelta(hours=22)).isoformat()),
            ("conv16", "c15", ChannelType.chat.value, "Инвестплан после продажи доли", (now - timedelta(hours=21)).isoformat()),
            ("conv17", "c8", ChannelType.chat.value, "Премиальный сервис отдельно от ликвидности", (now - timedelta(days=4)).isoformat()),
            ("conv18", "c5", ChannelType.chat.value, "Long-term investment intent после liquidity pitch", (now - timedelta(days=3, hours=6)).isoformat()),
        ]
    )
    messages: list[tuple[str, str, str, str, str]] = []
    messages.extend(
        _message_rows(
            "conv1",
            [
                ("client", "Добрый день. Хочу спокойно обсудить, куда разместить часть свободных средств.", now - timedelta(days=1, hours=2, minutes=25)),
                ("manager", "Добрый день, Иван. Могу собрать 3 сценария: вклад, консервативная облигационная часть и смешанный вариант.", now - timedelta(days=1, hours=2, minutes=18)),
                ("client", "Интересно, но важно не заходить в слишком высокий риск.", now - timedelta(days=1, hours=2, minutes=7)),
                ("manager", "Понял. Тогда акцент сделаю на сохранении ликвидности и доходности выше обычного вклада.", now - timedelta(days=1, hours=1, minutes=59)),
                ("client", "Да, и отдельно хочу увидеть, где можно быстро выйти в кэш без больших потерь.", now - timedelta(days=1, hours=1, minutes=46)),
                ("manager", "Сделаю это отдельной колонкой в сравнении. Также добавлю пример распределения на 6 и 12 месяцев.", now - timedelta(days=1, hours=1, minutes=39)),
                ("client", "Хорошо. И давайте без длинной презентации, лучше коротко и по цифрам.", now - timedelta(days=1, hours=1, minutes=27)),
                ("manager", "Принято. Завтра после 12:00 пришлю компактную таблицу и короткий вывод по каждому сценарию.", now - timedelta(days=1, hours=1, minutes=20)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv1b",
            [
                ("client", "Иван, еще отдельно вопрос по премиальной карте: какие сейчас travel-привилегии реально работают в поездках?", now - timedelta(hours=8, minutes=34)),
                ("manager", "Добрый день. Могу прислать короткий список: lounge, страховка, fast track и ограничения по пакетам.", now - timedelta(hours=8, minutes=29)),
                ("client", "Да, только коротко. Не хочу смешивать это с инвестиционным предложением и точно не хочу лишнего риска или сложных условий.", now - timedelta(hours=8, minutes=22)),
                ("manager", "Согласен, вынесу в отдельное сообщение и без лишних деталей.", now - timedelta(hours=8, minutes=18)),
                ("client", "Отлично. Если есть 2-3 самых полезных пункта, этого будет достаточно.", now - timedelta(hours=8, minutes=11)),
                ("manager", "Тогда соберу компактную подборку и пришлю отдельно вечером.", now - timedelta(hours=8, minutes=5)),
                ("client", "Хорошо, тогда жду отдельный короткий сервисный follow-up сегодня вечером.", now - timedelta(hours=7, minutes=59)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv2",
            [
                ("manager", "Ольга, добрый день. Подтвержу, что сегодня готов обсудить обновление портфеля.", now - timedelta(hours=6, minutes=35)),
                ("client", "Да, после 16:00 будет удобно.", now - timedelta(hours=6, minutes=31)),
                ("manager", "Отлично. Подготовлю сравнение по премиальному вкладу, защитной облигационной части и структурной идее.", now - timedelta(hours=6, minutes=25)),
                ("client", "Прошу без избыточного риска. Для меня важнее сохранность капитала, чем агрессивная доходность.", now - timedelta(hours=6, minutes=18)),
                ("manager", "Понял. Вынесу в начало только консервативные варианты и отдельно отмечу возможную доходность по каждому.", now - timedelta(hours=6, minutes=12)),
                ("client", "Хорошо. И если возможно, до звонка пришлите короткую рамку, чтобы я посмотрела между встречами.", now - timedelta(hours=6, minutes=5)),
                ("manager", "Да, отправлю краткое сравнение до 15:30 и в 16:00 созвонимся, чтобы пройтись по деталям.", now - timedelta(hours=5, minutes=57)),
                ("client", "Подходит. На звонке хочу отдельно обсудить, стоит ли держать часть ликвидности на коротком сроке.", now - timedelta(hours=5, minutes=51)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv5",
            [
                ("client", "Добрый вечер. Смотрю на валютные идеи, но не хочу заходить слишком резко.", now - timedelta(days=2, hours=1, minutes=12)),
                ("manager", "Понял вас. Можем зайти постепенно через брокерский счет и заранее ограничить долю валютной части.", now - timedelta(days=2, hours=1, minutes=2)),
                ("client", "Мне нужен понятный план: стартовая сумма, распределение и когда пересматривать позицию.", now - timedelta(days=2, minutes=51)),
                ("manager", "Соберу пошаговый сценарий на 3 шага и добавлю ориентиры для пересмотра через 30 и 90 дней.", now - timedelta(days=2, minutes=42)),
                ("client", "Хорошо. Важно, чтобы не было ощущения, что я покупаю на пике.", now - timedelta(days=2, minutes=34)),
                ("manager", "Тогда предложу поэтапный вход частями и отмечу, какие инструменты подойдут для умеренного риска.", now - timedelta(days=2, minutes=27)),
                ("client", "Отлично. И если будет удобно, давайте после вашего сообщения назначим короткую встречу на следующей неделе.", now - timedelta(days=2, minutes=18)),
                ("manager", "Сделаю. Завтра пришлю базовый план в чат, а затем предложу слоты на очную встречу.", now - timedelta(days=2, minutes=11)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv3",
            [
                ("manager", "Мария, добрый день. Хотел аккуратно вернуться к вопросу страховой защиты перед поездками.", now - timedelta(days=6, hours=3)),
                ("client", "Сейчас в плотном графике, не хочу вникать в длинные описания.", now - timedelta(days=6, hours=2, minutes=12)),
                ("manager", "Понял. Тогда не перегружаю: могу позже прислать совсем короткий вариант на 3 пункта.", now - timedelta(days=6, hours=2)),
                ("client", "Так будет лучше, спасибо.", now - timedelta(days=6, hours=1, minutes=46)),
                ("manager", "Верно ли понимаю, что актуально вернуться к теме уже ближе к поездке?", now - timedelta(days=5, hours=22, minutes=10)),
                ("client", "Да, лучше через несколько дней. И только в сообщении, без звонка.", now - timedelta(days=5, hours=14, minutes=30)),
                ("manager", "Принято. Напишу коротко в чат и без давления, когда срок будет ближе.", now - timedelta(days=5, hours=14, minutes=12)),
                ("client", "Спасибо, такой формат мне комфортен.", now - timedelta(days=5, hours=13, minutes=58)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv6",
            [
                ("manager", "Дмитрий, добрый день. Вижу крупный свободный остаток и хотел предложить варианты размещения ликвидности.", now - timedelta(days=1, hours=4, minutes=40)),
                ("client", "Добрый. Да, можно, но без длинной презентации. Нужен быстрый вывод по сути.", now - timedelta(days=1, hours=4, minutes=35)),
                ("manager", "Понял. Подготовлю один короткий блок: срок, ликвидность и ожидаемая доходность по трем вариантам.", now - timedelta(days=1, hours=4, minutes=29)),
                ("client", "Важно, чтобы можно было быстро сравнить вклад и облигационную альтернативу.", now - timedelta(days=1, hours=4, minutes=24)),
                ("manager", "Сделаю это в одном сообщении и отдельно отмечу, где есть быстрый выход.", now - timedelta(days=1, hours=4, minutes=18)),
                ("client", "Хорошо. Если задержитесь, напомните, во сколько ждать. Я буду между встречами.", now - timedelta(days=1, hours=4, minutes=13)),
                ("manager", "Отправлю до 14:30 и, если удобно, потом коротко созвонимся на 10 минут.", now - timedelta(days=1, hours=4, minutes=9)),
                ("client", "Созвон возможен, но только если будет совсем предметно и быстро.", now - timedelta(days=1, hours=4, minutes=6)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv4",
            [
                ("manager", "Елена, вижу, что у вас скоро поездка. Могу подобрать benefits по премиальной карте.", now - timedelta(hours=18, minutes=42)),
                ("client", "Да, это актуально. Особенно интересуют lounge, страховка и быстрый проход в поездках.", now - timedelta(hours=18, minutes=38)),
                ("manager", "Хорошо. Подберу пакет, где будут lounge, travel-страховка и приоритетный сервис.", now - timedelta(hours=18, minutes=32)),
                ("client", "Если можно, пришлите в коротком формате, чтобы я посмотрела с телефона.", now - timedelta(hours=18, minutes=28)),
                ("manager", "Сделаю компактный формат: 3 преимущества, условия и что включено по страховке.", now - timedelta(hours=18, minutes=24)),
                ("client", "Отлично. Еще интересно, есть ли что-то по повышенному кэшбэку в поездках.", now - timedelta(hours=18, minutes=19)),
                ("manager", "Да, добавлю отдельным пунктом travel-расходы и где будут максимальные бонусы.", now - timedelta(hours=18, minutes=15)),
                ("client", "Супер, спасибо. Если пришлете сегодня, я смогу быстро посмотреть вечером.", now - timedelta(hours=18, minutes=12)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv7",
            [
                ("client", "Наталья, добрый день. Подскажите, можно ли коротко собрать travel-benefits по карте перед поездкой?", now - timedelta(hours=11, minutes=18)),
                ("manager", "Да, подготовлю короткий список с lounge, страховкой и сервисом в поездках.", now - timedelta(hours=11, minutes=12)),
                ("client", "Супер. Мне важно, чтобы это было в одном сообщении и без длинных условий.", now - timedelta(hours=11, minutes=7)),
                ("manager", "Принял. Сделаю подборку в формате 3 пункта плюс что нужно активировать.", now - timedelta(hours=11, minutes=1)),
                ("client", "И отдельно, если можно, отметьте, где есть реальная сервисная ценность, а не просто формальные опции.", now - timedelta(hours=10, minutes=54)),
                ("manager", "Да, выделю именно практические benefits и добавлю короткий next step.", now - timedelta(hours=10, minutes=47)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv8",
            [
                ("manager", "Сергей, добрый день. Хотел предложить коротко обсудить размещение части свободной ликвидности на коротком сроке.", now - timedelta(hours=9, minutes=26)),
                ("client", "Добрый день. Можно, но только с очень понятным сравнением и без расплывчатых идей.", now - timedelta(hours=9, minutes=20)),
                ("manager", "Понял. Подготовлю короткий call-brief по вкладу, короткой облигационной альтернативе и срокам выхода.", now - timedelta(hours=9, minutes=14)),
                ("client", "Хорошо. И отдельно скажите, что имеет смысл удерживать в банке, а что оставить свободным.", now - timedelta(hours=9, minutes=10)),
                ("manager", "Да, это будет отдельным блоком: сколько держать ликвидным, сколько можно разместить без дискомфорта.", now - timedelta(hours=9, minutes=4)),
                ("client", "Тогда давайте созвонимся, если успеете прислать короткий ориентир заранее.", now - timedelta(hours=8, minutes=58)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv9",
            [
                ("client", "Ольга, добрый вечер. По премиальному сопровождению есть ощущение, что сервис стал менее предсказуемым.", now - timedelta(days=3, hours=4, minutes=32)),
                ("manager", "Спасибо, что сказали прямо. Давайте я коротко соберу, где именно были сбои, и вернусь с конкретным решением.", now - timedelta(days=3, hours=4, minutes=18)),
                ("client", "Да, лучше так. Пока не хочу, чтобы это смешивалось с портфелем и инвестиционными темами.", now - timedelta(days=3, hours=4, minutes=6)),
                ("manager", "Понял, разведем в отдельные контуры: сначала сервис, затем уже инвестиционный разговор.", now - timedelta(days=3, hours=3, minutes=58)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv10",
            [
                ("client", "Андрей, все еще думаю про валютную диверсификацию, но рынок выглядит нервно.", now - timedelta(days=2, hours=3, minutes=22)),
                ("manager", "Понимаю. Можем не заходить резко, а собрать staged сценарий: что сейчас, что позже и где границы по риску.", now - timedelta(days=2, hours=3, minutes=9)),
                ("client", "Это уже ближе. Только не хочу длинный pitch и ощущение, что меня торопят.", now - timedelta(days=2, hours=2, minutes=55)),
                ("manager", "Тогда пришлю очень короткую рамку: 2 варианта, уровень риска и что делать, если решите подождать.", now - timedelta(days=2, hours=2, minutes=41)),
                ("client", "Ок. Вернитесь позже, но коротко и без давления.", now - timedelta(days=2, hours=2, minutes=26)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv11",
            [
                ("client", "Татьяна, добрый день. Сервис по премиальному пакету снова сработал с задержкой, это уже не первый раз.", now - timedelta(hours=13, minutes=52)),
                ("manager", "Понимаю ваше раздражение и беру ситуацию на себя. Давайте сначала разберу сервисный сбой, а уже потом вернемся к финансовой части.", now - timedelta(hours=13, minutes=45)),
                ("client", "Именно. Сейчас меня больше волнует не вклад, а почему базовый сервис стал хуже.", now - timedelta(hours=13, minutes=36)),
                ("manager", "Справедливо. Я коротко вернусь с конкретным статусом и компенсационным решением.", now - timedelta(hours=13, minutes=28)),
                ("client", "Хорошо. Пока любые новые предложения неуместны, пока это не закрыто.", now - timedelta(hours=13, minutes=18)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv12",
            [
                ("client", "Павел, добрый день. Хочу понять, какие у вас есть варианты по накоплениям, но пока без конкретики.", now - timedelta(days=5, hours=2, minutes=22)),
                ("manager", "Добрый день. Чтобы не отправлять общий pitch, уточню два вопроса: горизонт и насколько важна ликвидность?", now - timedelta(days=5, hours=2, minutes=10)),
                ("client", "Пока не готов ответить подробно, нужно сначала самому собрать цифры.", now - timedelta(days=5, hours=1, minutes=57)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv13",
            [
                ("client", "Кира, добрый день. Через пару недель будет сделка, и нужно временно припарковать часть денег без жесткой блокировки.", now - timedelta(hours=9, minutes=42)),
                ("manager", "Понял. Тогда сначала смотрим на ликвидность и короткий срок, а уже после сделки отдельно возвращаемся к инвестиционному плану.", now - timedelta(hours=9, minutes=34)),
                ("client", "Да, именно так. Не хочу сейчас смешивать парковку ликвидности и долгосрочные идеи.", now - timedelta(hours=9, minutes=26)),
                ("manager", "Соберу одно короткое сравнение по двум коротким сценариям и отмечу, когда логично вернуться к investment discussion.", now - timedelta(hours=9, minutes=18)),
                ("client", "Отлично. И покажите, где можно выйти быстро, если сроки сделки сдвинутся.", now - timedelta(hours=9, minutes=9)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv14",
            [
                ("manager", "Роман, добрый день. Возвращаюсь аккуратно к теме краткосрочной ликвидности, которую вы поднимали в прошлый раз.", now - timedelta(days=18, hours=1, minutes=25)),
                ("client", "Сейчас не лучший момент, давайте позже.", now - timedelta(days=18, hours=1, minutes=13)),
                ("manager", "Понял. Тогда позже вернусь очень коротко, без деталей и без звонка, если так удобнее.", now - timedelta(days=18, hours=1, minutes=3)),
                ("client", "Да, только коротко и по существу.", now - timedelta(days=18, minutes=52)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv15",
            [
                ("client", "Анна, можно коротко по family travel-пакету? Нужны страховка и понятные benefits для поездок.", now - timedelta(hours=21, minutes=46)),
                ("manager", "Да, сделаю компактно: что входит по страховке, какие travel-benefits реально полезны и что нужно активировать.", now - timedelta(hours=21, minutes=38)),
                ("client", "Отлично. Только без длинных тарифных таблиц, лучше в 3-4 пункта.", now - timedelta(hours=21, minutes=27)),
                ("manager", "Принято, соберу мобильный формат и один следующий шаг, если тема откликнется.", now - timedelta(hours=21, minutes=16)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv16",
            [
                ("client", "Виктор, после продажи доли думаю про investment plan, но рынок выглядит слишком нервным для резкого входа.", now - timedelta(hours=20, minutes=42)),
                ("manager", "Тогда не делаем резкий вход. Могу разложить план на 3 шага: что можно сделать сейчас, что позже и где точки пересмотра.", now - timedelta(hours=20, minutes=33)),
                ("client", "Это хорошо. Мне нужен не pitch, а именно staged approach с контролем тайминга.", now - timedelta(hours=20, minutes=22)),
                ("manager", "Понял. Соберу сценарий по частям и отдельно отмечу, где можно остаться в ликвидности до следующего окна.", now - timedelta(hours=20, minutes=12)),
                ("client", "Отлично. Если будет коротко и предметно, готов обсудить уже на встрече.", now - timedelta(hours=20, minutes=4)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv17",
            [
                ("client", "Сергей, еще отдельно: по премиальному пакету нужны travel benefits, но не хочу смешивать это с разговором по ликвидности.", now - timedelta(days=3, hours=23, minutes=44)),
                ("manager", "Согласен, вынесу сервис в отдельный короткий follow-up и не буду мешать его с основным liquidity кейсом.", now - timedelta(days=3, hours=23, minutes=37)),
                ("client", "Отлично. Здесь нужен только короткий список без условий в несколько абзацев.", now - timedelta(days=3, hours=23, minutes=29)),
            ],
        )
    )
    messages.extend(
        _message_rows(
            "conv18",
            [
                ("client", "Дмитрий, кроме парковки ликвидности, думаю о более длинных инвестиционных идеях, но сейчас не хочу все смешивать.", now - timedelta(days=3, hours=5, minutes=34)),
                ("manager", "Полностью согласен. Тогда разделим: отдельно short-term liquidity и отдельно long-term investment framework.", now - timedelta(days=3, hours=5, minutes=22)),
                ("client", "Да, иначе это звучит как слишком широкий pitch. Лучше два четких шага.", now - timedelta(days=3, hours=5, minutes=12)),
                ("manager", "Так и сделаю: сначала короткий liquidity brief, а investment ideas вынесу в следующий контакт.", now - timedelta(days=3, hours=5, minutes=4)),
            ],
        )
    )
    storage.insert_messages(messages)
    storage.insert_conversation_insights(
        [
            (
                "conv1",
                "interested",
                "normal",
                "medium",
                12,
                8,
                (now + timedelta(days=1, hours=12)).isoformat(),
                "Отправить компактное сравнение трех сценариев после 12:00",
                ChannelType.chat.value,
                "comparison",
                "investments|liquidity|capital_preservation",
                "risk|liquidity|avoid_long_presentation",
                "p2|p3",
                "send_comparison|emphasize_liquidity|keep_message_short",
            ),
            (
                "conv1b",
                "neutral",
                "normal",
                "high",
                9,
                6,
                (now.replace(hour=19, minute=30, second=0, microsecond=0)).isoformat(),
                "Отдельно отправить короткую подборку по travel-benefits без смешения с инвестиционным кейсом",
                ChannelType.chat.value,
                "short",
                "travel|premium_card|service",
                "risk|avoid_topic_mixing|keep_message_short",
                "p1|p4",
                "keep_message_short|separate_topics|send_comparison",
            ),
            (
                "conv2",
                "neutral",
                "high",
                "high",
                6,
                5,
                (now.replace(hour=16, minute=0, second=0, microsecond=0)).isoformat(),
                "Созвон по обновлению портфеля и сравнению консервативных вариантов",
                ChannelType.call.value,
                "comparison",
                "capital_protection|deposit|structured_deals",
                "risk",
                "p3",
                "prepare_call|highlight_capital_protection|send_comparison",
            ),
            (
                "conv5",
                "interested",
                "normal",
                "medium",
                12,
                9,
                (now + timedelta(days=1)).isoformat(),
                "Отправить пошаговый FX-план и после этого предложить слоты встречи",
                ChannelType.chat.value,
                "detailed",
                "fx|brokerage|portfolio_growth",
                "timing_risk|aggressive_entry",
                "p2|p5",
                "send_comparison|prepare_call",
            ),
            (
                "conv3",
                "neutral",
                "low",
                "low",
                705,
                28,
                (now + timedelta(days=4)).isoformat(),
                "Вернуться позже коротким сообщением без давления",
                ChannelType.chat.value,
                "short",
                "insurance|soft_follow_up",
                "no_long_messages|avoid_pressure|no_call",
                "p4",
                "avoid_pressure|keep_message_short",
            ),
            (
                "conv6",
                "tense",
                "high",
                "speed_sensitive",
                5,
                4,
                (now.replace(hour=14, minute=30, second=0, microsecond=0)).isoformat(),
                "До 14:30 отправить одно короткое сравнение и при необходимости созвониться",
                ChannelType.chat.value,
                "comparison",
                "liquidity|deposit|bond_alternative",
                "avoid_long_presentation|needs_speed|liquidity",
                "p3|p2",
                "send_comparison|emphasize_liquidity|keep_message_short|prepare_call",
            ),
            (
                "conv4",
                "interested",
                "normal",
                "high",
                4,
                4,
                (now.replace(hour=20, minute=0, second=0, microsecond=0)).isoformat(),
                "Отправить сегодня вечером короткую подборку travel-benefits",
                ChannelType.chat.value,
                "short",
                "travel|premium_card|insurance|cashback",
                "mobile_format_only",
                "p1|p4",
                "keep_message_short|send_comparison",
            ),
            (
                "conv7",
                "interested",
                "normal",
                "high",
                7,
                6,
                (now.replace(hour=18, minute=30, second=0, microsecond=0)).isoformat(),
                "Отправить короткий travel-follow-up в одном сообщении с сервисной ценностью",
                ChannelType.chat.value,
                "short",
                "travel|service|premium_card",
                "avoid_long_terms|mobile_format_only",
                "p1|p4",
                "keep_message_short|send_comparison|emphasize_service",
            ),
            (
                "conv8",
                "neutral",
                "high",
                "speed_sensitive",
                8,
                5,
                (now.replace(hour=15, minute=0, second=0, microsecond=0)).isoformat(),
                "До звонка отправить короткий ориентир по размещению ликвидности и удержанию части средств",
                ChannelType.call.value,
                "comparison",
                "liquidity|retention|deposit",
                "needs_precision|avoid_long_presentation",
                "p3|p2",
                "prepare_call|send_comparison|emphasize_liquidity",
            ),
            (
                "conv9",
                "tense",
                "normal",
                "medium",
                18,
                12,
                (now + timedelta(days=2)).isoformat(),
                "Вернуться отдельно по сервисному quality issue, не смешивая с портфелем",
                ChannelType.chat.value,
                "short",
                "service|premium_card|retention",
                "trust|avoid_topic_mixing",
                "p1",
                "separate_topics|show_ownership|avoid_pressure",
            ),
            (
                "conv10",
                "neutral",
                "normal",
                "low",
                170,
                16,
                (now + timedelta(hours=5)).isoformat(),
                "Вернуться очень коротким staged follow-up без давления",
                ChannelType.chat.value,
                "short",
                "fx|growth|investments",
                "timing_risk|risk|avoid_pressure",
                "p5|p2",
                "avoid_pressure|keep_message_short|send_comparison",
            ),
            (
                "conv11",
                "negative",
                "critical",
                "speed_sensitive",
                4,
                3,
                (now + timedelta(hours=2)).isoformat(),
                "Сначала закрыть сервисный сбой и только потом возвращаться к удержанию остатков",
                ChannelType.call.value,
                "short",
                "retention|service|liquidity",
                "trust|negative_service|no_sales_push",
                "p1|p3",
                "show_ownership|prepare_call|avoid_pressure",
            ),
            (
                "conv13",
                "interested",
                "high",
                "high",
                8,
                5,
                (now + timedelta(hours=3)).isoformat(),
                "Подготовить short-term parking idea и отдельно обозначить окно для investment plan",
                ChannelType.call.value,
                "comparison",
                "liquidity|investments|capital_preservation",
                "timing|liquidity|avoid_topic_mixing",
                "p3|p2",
                "send_comparison|prepare_call|separate_topics",
            ),
            (
                "conv14",
                "neutral",
                "high",
                "low",
                960,
                22,
                (now + timedelta(hours=2)).isoformat(),
                "Сделать один аккуратный ping по ликвидности и проверить актуальность темы",
                ChannelType.call.value,
                "short",
                "liquidity|retention",
                "silent|avoid_pressure|no_long_messages",
                "p3",
                "keep_message_short|avoid_pressure",
            ),
            (
                "conv15",
                "interested",
                "normal",
                "medium",
                14,
                8,
                (now + timedelta(hours=20)).isoformat(),
                "Отправить mobile-first подборку family travel benefits",
                ChannelType.chat.value,
                "short",
                "family|travel|insurance",
                "complexity|mobile_format_only",
                "p4|p1",
                "keep_message_short|send_comparison",
            ),
            (
                "conv16",
                "interested",
                "high",
                "medium",
                11,
                7,
                (now + timedelta(hours=4)).isoformat(),
                "Прийти с staged investment plan и снять страх плохого тайминга",
                ChannelType.chat.value,
                "comparison",
                "investments|brokerage|growth",
                "timing_risk|risk|avoid_pressure",
                "p5|p2",
                "send_comparison|prepare_call|avoid_pressure",
            ),
            (
                "conv17",
                "neutral",
                "normal",
                "medium",
                16,
                9,
                (now + timedelta(hours=11)).isoformat(),
                "Отправить отдельный сервисный follow-up без смешения с liquidity conversation",
                ChannelType.chat.value,
                "short",
                "service|premium_card|travel",
                "avoid_topic_mixing|no_long_messages",
                "p1",
                "separate_topics|keep_message_short",
            ),
            (
                "conv18",
                "interested",
                "normal",
                "medium",
                13,
                8,
                (now + timedelta(hours=16)).isoformat(),
                "Развести short-term liquidity и long-term ideas на два контакта",
                ChannelType.chat.value,
                "comparison",
                "liquidity|investments|growth",
                "timing|avoid_long_presentation|avoid_topic_mixing",
                "p3|p2",
                "send_comparison|separate_topics|keep_message_short",
            ),
        ]
    )
    storage.insert_crm_notes(
        [
            (
                "n1",
                "c2",
                "m1",
                "t7",
                "Созвон состоялся. Клиент подтвердил интерес к продлению вклада и попросил сравнение с инвестиционным мандатом.",
                "follow_up",
                ChannelType.call.value,
                (now + timedelta(days=2)).isoformat(),
                (now - timedelta(hours=2)).isoformat(),
            ),
            (
                "n2",
                "c4",
                "m2",
                None,
                "Клиент ответил сдержанно, просит не перегружать сообщениями. Нужен мягкий follow-up через несколько дней.",
                "pending",
                ChannelType.chat.value,
                (now + timedelta(days=4)).isoformat(),
                (now - timedelta(days=1)).isoformat(),
            ),
            (
                "n3",
                "c10",
                "m2",
                None,
                "Клиент негативно оценивает сервис. До продуктового обсуждения нужно закрыть доверие и вернуться с конкретным решением по сервисному сбою.",
                "follow_up",
                ChannelType.call.value,
                (now + timedelta(hours=4)).isoformat(),
                (now - timedelta(hours=6)).isoformat(),
            ),
            (
                "n4",
                "c13",
                "m1",
                None,
                "Silent клиент. Следующий контакт должен быть очень коротким и только по теме краткосрочной ликвидности.",
                "follow_up",
                ChannelType.call.value,
                (now + timedelta(hours=6)).isoformat(),
                (now - timedelta(days=2)).isoformat(),
            ),
        ]
    )
    storage.insert_follow_ups(
        [
            (
                "f1",
                "c2",
                "n1",
                (now + timedelta(days=2)).isoformat(),
                "Подготовить сравнение вклада и инвест-мандата",
                0,
            ),
            (
                "f2",
                "c4",
                "n2",
                (now + timedelta(days=4)).isoformat(),
                "Вернуться с мягким сообщением про страховую защиту",
                0,
            ),
            (
                "f3",
                "c10",
                "n3",
                (now + timedelta(hours=4)).isoformat(),
                "Закрыть сервисный сбой и только затем возвращаться к удержанию остатков",
                0,
            ),
            (
                "f4",
                "c13",
                "n4",
                (now + timedelta(hours=6)).isoformat(),
                "Отправить очень короткий retention ping по ликвидности",
                0,
            ),
        ]
    )
    storage.insert_feedback(
        [
            (
                "fb1",
                "rec-portfolio-1",
                "m1",
                "priority_recommendation",
                "accepted",
                "Логика понятна, беру в работу.",
                (now - timedelta(hours=3)).isoformat(),
            ),
            (
                "fb2",
                "rec-retention-4",
                "m2",
                "next_best_action",
                "edited",
                "Сделаю более мягкий контакт, чем предлагалось.",
                (now - timedelta(hours=8)).isoformat(),
            ),
            (
                "fb3",
                "rec:task:task-3",
                "m1",
                "manager_work_item",
                "c5",
                "conv6",
                "accepted",
                "Ликвидность берем в работу как отдельный короткий оффер.",
                "Короткий liquidity brief",
                (now - timedelta(hours=2, minutes=20)).isoformat(),
            ),
            (
                "fb4",
                "rec:task:task-4",
                "m2",
                "manager_work_item",
                "c4",
                "conv3",
                "edited",
                "Нужен еще более мягкий тон и только chat.",
                "Short soft follow-up",
                (now - timedelta(hours=7, minutes=10)).isoformat(),
            ),
            (
                "fb5",
                "rec:communication:conv11",
                "m2",
                "manager_work_item",
                "c10",
                "conv11",
                "rejected",
                "Сначала решаем сервис, любой sales follow-up сейчас неуместен.",
                "Service recovery only",
                (now - timedelta(hours=1, minutes=35)).isoformat(),
            ),
            (
                "fb6",
                "rec:task:task-14",
                "m1",
                "manager_work_item",
                "c13",
                "conv14",
                "accepted",
                "Делаем аккуратный возврат в коммуникацию сегодня.",
                "Retention ping",
                (now - timedelta(hours=1, minutes=5)).isoformat(),
            ),
            (
                "fb7",
                "rec:opportunity:c15:conv16",
                "m1",
                "manager_work_item",
                "c15",
                "conv16",
                "edited",
                "Нужен staged plan вместо прямого investment pitch.",
                "Stage-by-stage entry",
                (now - timedelta(minutes=55)).isoformat(),
            ),
        ]
    )
